name: auvnet_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.4
  equatable: ^2.0.7
  # shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/nawel.png
  android: true
  ios: true
  web: false
  android12:
    color: "#FFFFFF"
    image: assets/images/nawel.png